# ======================
# docker-compose.yml
# ======================
version: '3.8'

services:
  sui-chatbot:
    build: .
    container_name: sui_chatbot_api
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - MAX_INPUT_LENGTH=${MAX_INPUT_LENGTH}
      - AI_MODEL=gpt-${AI_MODEL}
      - AI_MAX_TOKENS=${AI_MAX_TOKENS}
      - AI_TEMPERATURE=${AI_TEMPERATURE}
      - LOG_LEVEL=${LOG_LEVEL}
      - APP_NAME=${APP_NAME}
      - VERSION=${VERSION}
      - DEBUG=${DEBUG}
      - HOST=${HOST}
      - PORT=${PORT}
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/api/v1/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  